### ISSUE TITLE
Could the mutex be removed and this simplified by passing an owned `self` instead of a mutable reference?

### ISSUE THREAD

**Issue by BitcoinZavior** [LtbLightning/payjoin-ffi#10]
> There are a few reasons to use a mutexGaurd **PayjoinProposal.** This is the `PayjoinProposal` struct without mutex_gaurd,
> 
> ```
> pub struct PayjoinProposal {
>    internal: PdkPayjoinProposal,
> }
> impl PayjoinProposal {
>    pub fn contribute_witness_input(&mut self, txout: TxOut, outpoint: OutPoint) {
>     // let mut guard = self.get_proposal_mutex_guard();
>     self.internal.contribute_witness_input(txout.into(), outpoint.into());
>     // [guard.as](http://guard.as/)_mut().unwrap().contribute_witness_input(txout.into(), outpoint.into());
>    }
> }
> ```
> 
> ```
> 1, In the above function we have to use `&mut self` in the parameter,
>   but unfortunetly, `uniffi` , doesn't allow that.
> 2, prepare psbt takes a `mut self`, that will be a problem as well,
>   since uniffi requires a `&self` in the function for properly generating
>   binding code.
> ```
> 
> In short mutuxes are used to ensure safe and synchronised access to shared resources in multi-threaded or multi-process programs. But good to keep checking, I am sure there are instance where we can do without a mutex. FYI I started off with tons more mutex' and removed after some analysis. If you come across any which you are sure dont need ro be a mutex please point it out.

> Could the mutex be removed and this simplified by passing an owned `self` instead of a mutable reference?

_Originally posted by @DanGould in https://github.com/LtbLightning/payjoin-ffi/pull/2#discussion_r1344491929_
     
     

> Yes, if we dont want to use mutex here we can remove it. probably worth looking if there are other instances where mutex is not required. I will updated in a future commit in the python branch.

**Comment by DanGould** [comment]
This is fixed because the new `contribute_inputs` function moves the state machine forward with an owned `self` instead of a mutable reference
