### ISSUE TITLE
bdk and payjoin integration error

### ISSUE THREAD

**Issue by BitcoinZavior** [LtbLightning/payjoin-ffi#25]
Using `bdk` with `payjoin` results in `payjoin` throwing `The receiver sent an invalid response: proposed transaction outputs contain key paths`

Steps to replicate: Follow the steps for Running the integration tests: https://github.com/LtbLightning/payjoin-ffi?tab=readme-ov-file#running-the-integration-test

Run the integration test which uses bdk: `cargo test --package payjoin_ffi --test bdk_integration v1_to_v1_full_cycle`
This will result in `ResponseError { message: "The receiver sent an invalid response: proposed transaction outputs contain key paths" }` 

Versions: This uses the pre-alpha release v0.29  https://github.com/bitcoindevkit/bdk/releases/tag/v0.29.0

**Comment by BitcoinZavior** [comment]
Depends on https://github.com/payjoin/rust-payjoin/pull/270

**Comment by DanGould** [comment]
This should be closed by #28 and [payjoin v0.17.0](https://github.com/payjoin/rust-payjoin/releases/tag/payjoin-0.17.0)
